class Api {
  static getConfig = 'v1/config/';
  static getCommercialTemplate = entity =>
    `v2/request/commercial_request_templates/?entity=${entity}`;
  static getCustomPromocionalImages = id =>
    `v2/promotions/custom_promotional_images/?celebrity=${id}`;
  static postViewedCustomImg = id =>
    `v2/promotions/custom_promotional_images/?promo_img=${id}`;
  static getAllPromoImgs = 'v2/promotions/celeb_promo_templates/'
  static getAllCustomPromoImgs = 'v2/promotions/celeb_custom_promo_imgs'
  static getFeaturedStars = 'v2/user/celebrity_display/';
  static getCelebList = 'v2/user/fan/celebrity_list/get_list/';
  static getTrendingStars = 'v2/user/trending_stars/';
  static authGetCelebList = 'v2/user/fan/celebrity_list/';
  static getProfessionsList = 'v2/user/filtered_professions/';
  static getAllProfessions = 'v2/user/professions/';
  static getGroupTypes = 'v1/user/group_types/';
  static getVideosList = 'v2/request/featured_videos/';
  static login = 'v1/user/login/';
  static register = 'v2/user/register/';
  static getSuggestionList = 'v1/user/fan/suggestion_list/';
  static socialMediaLogin = 'v1/user/socialsignup/';
  static authGetCelebDetails = 'v2/user/user_details/';
  static getCelebDetails = id => `v2/user/user_details/${id}/get_details/`;
  static getUserFavourites = 'v2/user/fan/favourite_stars/';
  static getUserVideos = 'v2/request/request_list/';
  static getRequestDetails = 'v2/request/stargramz/';
  static followCelebrity = 'v1/user/fan/celebrity_follow/';
  static getOccasionList = 'v2/request/occasion_list/';
  static downloadVideo = videoId => `${env('SERVER_URL')}download/${videoId}`;
  static setVideoView = 'v1/request/readvideo/';
  static setTags = 'v2/user/tags/';
  static otherRelation = 'v1/request/other_relation/';
  static getEphemeralKey = 'v1/payments/generatekey/';
  static tipPayment = 'v2/payments/paytip/';
  static createCharge = 'v1/payments/createcharge/';
  static starsonaRequest = 'v1/request/stargramz/';
  static starsonaVideo = 'v1/request/stargramz_video/';
  static getSourceList = 'v1/payments/stripe_cards/';
  static modifySourceList = 'v1/payments/attach_detach_source/';
  static forgotPassword = 'v1/user/forgotpassword/';
  static resetPassword = 'v1/user/resetpassword/';
  static getAWSVideo = 'v1/user/get_signed_url/?key=';
  static modifyUserDetails = 'v2/user/user_details';
  static modifySocialLinks = 'v1/user/social_links/';
  static updateGroupAccount = 'v1/user/group_account/';
  static updateNotification = 'v1/user/notification_settings/';
  static updatePhoto = 'v2/user/profileimages/';
  static celebrityProfile = 'v2/user/celebrity_profile/';
  static getImageCredentials = imageType =>
    `v1/user/signed_url/?extension=${imageType}&key=profile_images&file_type=image`;
  static getawsCredentials = (key, extension, fileType, requestId) =>
    `v1/user/signed_url/?extension=${extension}&key=${key}&file_type=${fileType}${
      requestId ? `&request_id=${requestId}` : ''
    }`;
  static getOpenAwsCredentials = (key, extension, fileType) => `v2/user/open_file_upload/?extension=${extension}&key=${key}&file_type=${fileType}`;
  static changeRequestStatus = 'v1/request/change_request_status/';
  static rating = 'v1/user/fan/celebrity_rating/';
  static requestFeedback = 'v2/request/feedback/';
  static contactSupport = 'v2/user/contact_support/';
  static reportAbuse = 'v1/user/fan/celebrity_abuse/';
  static reactionAbuse = 'v1/request/reaction_abuse/';
  static stripeRegistration = 'v1/payments/getstripeurl/';
  static checkStripe = 'v1/payments/stripe_dashboard/';
  static deleteStripe = 'v1/user/remove_stripe/';
  static changePassword = 'v2/user/changepassword/';
  static getEarningsList = 'v2/payments/earnings_list/';
  static requestReferral = 'v1/user/referral_request/';
  static getReferralList = 'v1/user/referral_list/';
  static getCommentsList = 'v1/request/comments';
  static addComment = 'v1/request/comments/';
  static groupMembersList = 'v1/user/group_list/';
  static celebrityGroupFollow = 'v1/user/join_group/';
  static fanGroupFollow = 'v1/user/fan/group_follow/';
  static getGroupMembers = 'v1/user/get_members/';
  static getOtpCode = 'v1/user/validate_mobile/';
  static validateOtpCode = 'v1/user/verify_mobile/';
  static celebRepresentative = 'v1/user/celebrity_representative/';
  static getReactions = 'v2/request/reactions/';
  static getStarReaction = 'v2/request/reactions_full_listing/';
  static getGroupsList = 'v1/user/group_account/';
  static groupTypeListing = 'v1/user/active_group_types/';
  static createGroupNotification = 'v1/notification/new_group_notification/';
  static twitterLogin = 'v1/user/twitter_integration/';
  static twitterOauth = 'v1/user/twitter_login';
  static validatePromo = 'v1/user/referral_validate/';
  static getSubCategoryList = 'v2/user/professions/?parent=false';
  static getGroupDetails = groupID =>
    `v1/user/user_details/${groupID}/get_details`;
  static getGroupMemberList = groupID =>
    `v1/user/group_list/?account=${groupID}`;
  static dashboardUpdate = 'v2/user/dashboard_update/';
  static dashBoard = 'v2/user/celebrity_dashboard/';
  static notificationViewed = 'v2/user/settings_viewed/';
  static updateUnseenCount = 'v1/user/update_unseen_count/';
  static getRecentActivity = 'v2/user/recent_activity/';
  static favoriteVideo = 'v2/request/request_favorites/';
  static toggleActivityVisibility = 'v2/user/activity_public_visibility/';
  static hideVideoFromProfile = 'v2/request/video_hide_from_public/';
  static videoPublicity = 'v2/request/make_booking_private/';
  static reactionComplete = 'v2/request/reaction_process/';
  static sharePromoProfile = 'v2/promotions/share_profile/';
  static shareCustomPromoImg = 'v2/promotions/share_custom_img/';
  static getVideoPublicMainData = userId =>
    `v2/request/stargramz/${userId}/get/`;
  static getRecentActivityPublicList = userId =>
    `v2/user/recent_activity/${userId}/public_list/`;
  static promotionList = 'v2/promotions/share_profile/';
  static getTagDetails = 'v2/user/tag_details/';
  static increaseTagView = 'v2/user/add_tag_view/';
  static getTagsList = 'v2/user/user_tags';
  static celebrityShare = 'v2/user/celebrity_share/';
  static getReferralDetails = 'v2/user/referral_details/';
  static charity = 'v2/user/charity/';
  static fundRaiser = 'v2/user/fund_raiser/';
  static commercialBooking = 'v2/request/commercial_request/';
  static commercialToggle = 'v2/user/allow_commercial/';
  static getDynamicFilters = 'v2/user/active_dynamic_links/';
  static postDynamicFilters = 'v2/user/add_link_view/';
  static fanCelebritySuggestion = '/v2/user/fan_celebrity_suggestions/';
  static validatePromocode = 'v2/promocode/validate/';
  static getSaleMessages = 'v2/user/sale_messages/';
  static alertfan = 'v2/user/alert_fan/';
  static topProfessions = 'v2/user/top_professions/';
  static nearestStars = 'v2/user/nearest_celebrities/';
  static services = 'v2/user/services/';
  static directMessage = 'v2/message/direct_message/';
  static loginWithToken = 'v2/user/login_token/';
  static socialShoutout = 'v2/social_media/social_media_request/';
  static digitalGoods = 'v2/fun_stuff/celebrity_fun_stuff/';
  static sendDigitalGoods = 'v2/fun_stuff/request_fun_stuff/';
  static sendProducts = 'v2/products/celebrity_product/';
  static requestProduct = 'v2/products/request_product/';
  static fetchSocialDetails = 'v2/social_media/social_media_list/';
  static updateSocial = 'v2/social_media/social_media_adding/';
  static bookingInitiate = 'v2/request/booking_try/';
  static checkStarUrlAvailability = 'v2/user/url_availability/';
  static emailRegister = 'v2/user/email_register/';
  static earningsDownload = 'v2/payments/earnings_data/';
  static starConcierge = 'v2/promotions/get_concierge/';
  static courses = 'v2/promotions/get_course/';
  static articleOrIdeas = 'v2/promotions/get_article_idea/';
  static markCourse = 'v2/promotions/add_section/';
  static getFreshDeskToken = 'v2/user/get_jwt/';
  static pageColors = 'v2/user/page_colors/';
  static pageFonts = 'v2/user/page_fonts/';
  static backgroundImages = 'v2/user/background_images/';
  static socialInteractionList = 'v2/user/social_media_interactions/';
  static recentRequestList = 'v2/user/recent_bookings/';
  static galleryImage = 'v2/user/gallery/';
  static specialUrl = 'v2/user/check_celebrity/';
  static starSeoList = 'v2/user/seo_user_details/';
  static newProductList = 'v2/user/new_product_listing/';
  static testimonial = 'v2/user/testimonials/';
  static presslogo = 'v2/promotions/press_logo/';
  static favRequests = 'v2/request/best_requests/';
  static fanDetails = 'v2/user/fan_details/';
  static clarifyDet = 'v2/request/clarification/';
  static discount = 'v2/user/discount/';
  static analytic = 'v2/request/analytics/';
  static getDiscount = 'v2/user/discount_public/';
  static promoCatList = 'v2/promotions/promotion_category_list/';
  static promoImgCount = 'v2/promotions/promo_image_count/';
  static promoImgViewCount = 'v2/promotions/promo_image_view/';
  static extStoreSett = 'v2/external/external_api/';
  static similarStars = 'v2/user/similar_stars/';
  static topProducts = 'v2/user/top_products/';
  static getRating = 'v2/user/get_rating/';
  static last2Msg = '/v2/message/last_message/';
  static suggestion = 'v2/user/suggestions/';
  static crosstalent = 'v2/user/cross_talent/';
  static starCountries = 'v2/user/available_countries/';
  static userLanguages = 'v2/user/language/';
  static featuredExp = 'v2/user/featured_products/';
  static performance = 'v2/request/component_analytics/';
  static commercialoffering = 'v2/request/celebrity_commercial_request/';
  static downloadBookFile = 'v2/fun_stuff/download/';
  static getEntity = 'v2/partner/partner_config/';
  static partnerList = 'v2/partner/sharing_entity/';
  static shareEntity = 'v2/partner/celebrity_entity';
  static termsPolicy = 'v2/partner/terms_policy/';
  static top4stars = 'v2/partner/top_entity_stars';
  static countryList = 'v2/user/country_list/';
  static myStars = 'v2/user/my_stars/';
  static myStarsRequest = 'v2/request/public_request_list/';
  static regCollector = 'v2/user/interested_fans/';
  static optileList = 'v2/payments/optile_pay_types/';
  static optilePayment = 'v2/payments/optile_payment/';
  static followSuggestions = '/v2/user/fan/follow_suggestions/';
  static moreTips = '/v2/promotions/request_tips/';
  static getV3Users = '/v2/user/v3_experiences/';
  static isCelebProfileComplete = '/v2/user/is_celebrity_completed/'
  static postExternalAudio = '/v2/request/external_audio_recording/';
  static generalPromocode = 'v2/promocode/general_promocodes/';
}

export default Api;
