# serverless deploy --stage staging
service: next-geolocation
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: staging
  memorySize: 256
  timeout: 30
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  edgeRedirect:
    handler: handler.edgeRedirect
