
Cypress.on("uncaught:exception", err => !err.message.includes("ResizeObserver"));
const defaultMsg = 'Cypress testing overcome char limit'
const talentToken = 'fdb6331e8e9bc97627bef1d543b2d7b227e977d8'
context('Talent fulfilling bookings', {
  defaultCommandTimeout: 10000
}, () => {
  before(() => {
    cy.cancelAllBookingsPerUser(talentToken)
  })
  beforeEach(() => {
    localStorage.setItem('data', JSON.stringify({"user":{"first_name":"test","last_name":"suite","nick_name":"testsuit","id":"1aMZkBbW","email":"test_suite@gmail.com","authentication_token":"fdb6331e8e9bc97627bef1d543b2d7b227e977d8","status":1,"sign_up_source":1,"images":[{"id":"BeX7Nldy","image_url":"https://dxjnh2froe2ec.cloudfront.net/images/profile/FILE_1642629277GTEKTWD9.jpeg","thumbnail_url":"https://dxjnh2froe2ec.cloudfront.net/images/profile/thumbnail_FILE_1642629277GTEKTWD9.jpeg","photo":"FILE_1642629277GTEKTWD9.jpeg","thumbnail":"thumbnail_FILE_1642629277GTEKTWD9.jpeg","medium_thumbnail":null,"medium_thumbnail_url":null}],"profile_photo":null,"avatar_photo":{"id":"BeX7Nldy","image_url":"https://dxjnh2froe2ec.cloudfront.net/images/profile/FILE_1642629277GTEKTWD9.jpeg","thumbnail_url":"https://dxjnh2froe2ec.cloudfront.net/images/profile/thumbnail_FILE_1642629277GTEKTWD9.jpeg","photo":"FILE_1642629277GTEKTWD9.jpeg","thumbnail":"thumbnail_FILE_1642629277GTEKTWD9.jpeg","medium_thumbnail":null,"medium_thumbnail_url":null},"show_nick_name":true,"completed_fan_unseen_count":0,"fresh_desk_jwt":"eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiZGV2X3VzZXIiLCJlbWFpbCI6ImRldmVtYWlsQGVtYWlsLmNvbSIsImV4cCI6MTY0MjY5NTExNn0.R3yRvA4oIiaJTsuwG8IMgJK2bVuvoO2_zlqZO4w5_Ng","getstream_token":"eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMTEzNjcifQ.w66J47BuaF2XPtH_Gcq-jWPomB4RfN-CdyzMCckYiUU","role_details":{"id":"1aK8qRbQ","role_code":"R1002","role_name":"Celebrity","is_complete":true},"celebrity":true,"partner_data":{"partner_entity_domain":"https://staging.ttwithme.com","entity_id":"STARSONA-US-1","name":"Starsona - US","region_id":"STARSONA-US","base_date_format":"MM/DD/YYYY"},"show_fan_home":true,"notification_settings":{"id":10032,"user":"1aMZkBbW","timezone":"Europe/Lisbon","timezone_name":null,"celebrity_starsona_request":true,"celebrity_starsona_message":true,"celebrity_account_updates":true,"fan_account_updates":true,"fan_starsona_messages":true,"fan_starsona_videos":true,"fan_email_starsona_videos":true,"email_notification":false,"secondary_email":null,"mobile_country_code":"1","mobile_number":"3473453324","mobile_notification":true,"mobile_verified":false,"verification_uuid":null,"is_viewed":false,"whatsapp_notification":false}},"celebrity_details":{"pending_requests_count":18,"weekly_limits":100,"rate":"32.00","description":"","in_app_price":"31.99","rating":"0.00","follow_count":0,"charity_visibility":true,"availability":true,"featured":false,"remaining_limit":99,"stripe_user_id":null,"check_payments":false,"activation_date":null,"inactivated_date":null,"allow_comment":true,"allow_reaction":true,"allow_rating":true,"off_limit_topics":null,"page_design":false,"related_videos":[],"profession_details":[]}}))
    cy.intercept('**/api/v2/request/request_list/**').as('bookings')
    cy.intercept('https://starsona-stb-usea1.s3-accelerate.amazonaws.com/').as('s3Upload')
  })
  describe('is able to fulfill simple requests', () => {

    it ('fulfills social bookings', () => {
      cy.generateSocialMedia()
      cy.wait(5000)
      cy.intercept('https://app.staging.starsona.com/api/v2/social_media/social_media_request/').as('socialMediaCompleted')
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.get('.n-count').should('be.visible')
      cy.contains('Social media interaction for', { matchCase: false }).click({force: true})
      cy.get('textarea').type('Cypress testing')
      cy.contains('Mark delivered', { matchCase: false }).click()
      cy.wait('@socialMediaCompleted')
      cy.contains('You have completed a Social media interaction', { matchCase: false })
      cy.get('img[data-cy=promo-image-response]').should('have.attr', 'src').should('include', 'images/promotional_images')
      cy.contains('Next Request', { matchCase: false })
    })

    it ('fulfills a merch booking', () => {
      cy.generateMerch()
      cy.wait(5000)
      cy.intercept('https://app.staging.starsona.com/api/v2/products/request_product/').as('merchCompleted')
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.get('.n-count').should('be.visible')
      cy.contains('Merch purchase for', { matchCase: false }).click({force: true})
      cy.contains('Tracking number', { matchCase: false }).parent().get('input').type(123)
      cy.contains('Select a shipping carrier', { matchCase: false }).click({ force: true })
      cy.contains('UPS', { matchCase: false }).click({ force: true })
      cy.contains('Mark shipped', { matchCase: false }).click({ force: true })
      cy.wait('@merchCompleted')
      cy.get('img[data-cy=promo-image-response]').should('have.attr', 'src').should('include', 'images/promotional_images')
      cy.contains('You have completed a merch order', { matchCase: false })

    })
    it ('fulfills a dm booking', () => {
      cy.intercept('https://app.staging.starsona.com/api/v2/message/direct_message/').as('dmCompleted')
      cy.generateDm()
      cy.wait(5000)
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.get('.n-count').should('be.visible')
      cy.contains('Direct Message (DM) for').click({ force: true })
      cy.get('textarea').type(defaultMsg)
      cy.contains('Reply').click({force: true})
      cy.wait('@dmCompleted')
      cy.contains('Next Request', { matchCase: true })
    })

    it ('fulfills a dm booking by marking as viewed', {
      defaultCommandTimeout: 30000
    },() => {
      cy.intercept('https://app.staging.starsona.com/api/v2/message/direct_message/').as('dmCompleted')
      cy.generateDm()
      cy.wait(5000)
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.get('.n-count').should('be.visible')
      cy.contains('Direct Message (DM) for').click({ force: true })
      // cy.get('textarea').type(defaultMsg)
      // cy.contains('Reply').click({force: true})
      cy.contains('Mark viewed, but').forceClick()
      cy.wait('@dmCompleted')
      cy.contains('Next Request', { matchCase: true }).forceClick()
      cy.contains('Want more requests')
      cy.fanLogin()
      cy.visit('/testsuit/chat')
      cy.get('textarea')
    })
  })
  describe('is able to fulfill all fun stuffs', () => {


    it ('fulfills a video recording fun stuff', () => {
      cy.generateFunStuff()
      cy.intercept('https://app.staging.starsona.com/api/v1/user/signed_url/?extension=mp4&key=request_files&file_type=video**').as('funSignedUrl')
      cy.intercept('https://app.staging.starsona.com/api/v2/fun_stuff/request_fun_stuff/').as('funPost')
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.contains('Fun Stuff item request for', { matchCase: false }).click({ force: true })
      cy.contains('Start recording').click({ force: true })
      cy.wait(4000)
      cy.contains('Stop recording', { matchCase: false }).click({force: true})
      cy.contains('Complete order').click({ force: true })
      cy.wait('@funSignedUrl')
      cy.wait('@s3Upload')
      cy.wait('@funPost')
      cy.contains('Great Job!', { matchCase: false })
      cy.contains('Next Request', { matchCase: false })
      cy.get('img[data-cy=promo-image-response]').should('have.attr', 'src').should('include', 'images/promotional_images')
    })

    it ('fulfills a audio recording fun stuff', () => {
      cy.generateAudioFunStuff()
      cy.intercept('https://app.staging.starsona.com/api/v1/user/signed_url/**').as('funSignedUrl')
      cy.intercept('https://app.staging.starsona.com/api/v2/fun_stuff/request_fun_stuff/').as('funPost')
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.contains('Fun Stuff item request for', { matchCase: false }).click({ force: true })
      cy.contains('Record audio file', { matchCase: false }).click({ force: true })
      cy.wait(4000)
      cy.contains('Stop recording', { matchCase: false }).click({force: true})
      cy.contains('Complete order', { matchCase: false }).click({ force: true })
      cy.wait('@funSignedUrl')
      cy.wait('@s3Upload')
      cy.wait('@funPost')
      cy.contains('Great Job!', { matchCase: false })
      cy.contains('Next Request', { matchCase: false })
      cy.get('img[data-cy=promo-image-response]').should('have.attr', 'src').should('include', 'images/promotional_images')
    })

    it ('fulfills a text based fun stuff', () => {
      cy.generateTextFunStuff()
      cy.intercept('https://app.staging.starsona.com/api/v1/user/signed_url/**').as('funSignedUrl')
      cy.intercept('https://app.staging.starsona.com/api/v2/fun_stuff/request_fun_stuff/').as('funPost')
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.contains('Fun Stuff item request for', { matchCase: false }).click({ force: true })
      cy.get('textarea').type('Cypress fulfilling the fun stuff booking')
      cy.contains('Complete order', { matchCase: false }).click({ force: true })
      cy.contains('Great Job!', { matchCase: false })
      cy.contains('Next Request', { matchCase: false })
      cy.get('img[data-cy=promo-image-response]').should('have.attr', 'src').should('include', 'images/promotional_images')
    })

    it ('fulfills a file upload fun stuff', () => {
      cy.fileUploadFunStuff()
      cy.intercept('https://app.staging.starsona.com/api/v1/user/signed_url/**').as('funSignedUrl')
      cy.intercept('https://app.staging.starsona.com/api/v2/fun_stuff/request_fun_stuff/').as('funPost')
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.contains('Fun Stuff item request for', { matchCase: false }).click({ force: true })
      cy.get('textarea').type('Cypress fulfilling the fun stuff booking')
      cy.get('#fileUpload').attachFile('test.txt')
      cy.contains('test.txt', { matchCase: false })
      cy.contains('Complete order', { matchCase: false }).click({ force: true })
      cy.contains('Great Job!', { matchCase: false })
      cy.contains('Next Request', { matchCase: false })
      cy.get('img[data-cy=promo-image-response]').should('have.attr', 'src').should('include', 'images/promotional_images')
    })

    it ('fulfills a photo upload fun stuff', () => {
      cy.photoUploadFunStuff()
      cy.intercept('https://app.staging.starsona.com/api/v1/user/signed_url/**').as('funSignedUrl')
      cy.intercept('https://app.staging.starsona.com/api/v2/fun_stuff/request_fun_stuff/').as('funPost')
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.contains('Fun Stuff item request for', { matchCase: false }).click({ force: true })
      // cy.get('textarea').type('Cypress fulfilling the fun stuff booking')
      cy.get('#fileUpload').attachFile('test.png')
      cy.contains('test.png', { matchCase: false })
      cy.contains('Complete order', { matchCase: false }).click({ force: true })
      cy.contains('Great Job!', { matchCase: false })
      cy.contains('Next Request', { matchCase: false })
      cy.get('img[data-cy=promo-image-response]').should('have.attr', 'src').should('include', 'images/promotional_images')
    })

    it('fulfills a shoutout', () => {
      cy.generateShoutout()
      cy.wait(5000)
      cy.intercept('https://app.staging.starsona.com/api/v1/user/signed_url/?extension=mp4&key=stargram_videos&file_type=video**').as('signedUrl')
      cy.intercept('https://app.staging.starsona.com/api/v1/request/stargramz_video/').as('finishing')
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.get('.n-count').should('be.visible')
      cy.contains('Birthday shoutout for', { matchCase: false }).click({force: true})
      cy.contains('Start recording', { matchCase: false }).click({force: true})
      cy.contains('Stop recording', { matchCase: false }).click({force: true})
      cy.contains('Continue', { matchCase: false }).click({force: true})
      cy.wait('@signedUrl')
      cy.wait('@finishing')
      cy.contains('Perfect', { matchCase: false })
      cy.contains('Next Request', { matchCase: false })
      cy.get('img[data-cy=promo-image-response]').should('have.attr', 'src').should('include', 'images/promotional_images')
    })

  })

  describe('Commercial bookings', () => {
    beforeEach(() => {
      cy.intercept('https://app.staging.starsona.com/api/v2/request/commercial_request/').as('commercialApproval')
    })
    it ('accept the terms', () => {
      cy.generateCommercial()
      cy.wait(5000)
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.get('.n-count').should('be.visible')
      cy.contains('Commercial request for').forceClick()
      cy.contains('Accept terms')
      cy.wait('@commercialApproved')
      cy.contains('Request updated')
    })
  })

  describe('Clarifications', () => {
    beforeEach(() => {
      cy.intercept('https://app.staging.starsona.com/api/v2/request/clarification/').as('clarification')
    })
    it ('Allows the talent to ask for clarifications', () => {
      cy.generateSocialMedia()
      const clarificationContent = 'Cypress clarification'
      cy.wait(5000)
      cy.visit('/manage/bookings')
      cy.wait('@bookings')
      cy.get('.n-count').should('be.visible')
      cy.contains('Social media interaction for').forceClick()
      cy.contains('Ask Purchaser a Q').forceClick()
      cy.get('textarea').type(clarificationContent)
      cy.contains('Send').forceClick()
      cy.wait('@clarification')
      cy.contains(clarificationContent)
    })
  })
})
