import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script';

import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [text, setText] = useState('');
  function printScriptTextContent() {
  alert('print function called');
  var xhr = new XMLHttpRequest();
  xhr.open("GET","https://appx/web-view.min.js")
  xhr.onreadystatechange = function () {
    alert('xhr ready')
    if(xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
      alert('xhr done')
      alert('xhr response: ' + xhr.responseText);
      console.log("the script text content is",xhr.responseText);
      setText(xhr.responseText);
    }
  };
  xhr.send();
}
  const getScript = () => {
    alert('axios get script called');
    axios.get('https://appx/web-view.min.js').then(resp => {
      alert('axios get script done' + JSON.stringify(resp.data));
      setText(JSON.stringify(resp.data));
    }).catch(e => {
      alert('axios get script error: ' + e)
      alert('axios get script error: ' + JSON.stringify(e))
      alert('axios get script error: ' + JSON.stringify(e.response))
    });
  }
  useEffect(() => {
		alert('inside usseEffect');
		const script = document.createElement('script');
		script.type = 'text/javascript';
    script.id = 'vodascript';
    getScript();
    // printScriptTextContent();
		script.addEventListener('load', () => {
			alert('loaded script');
      // setText(document.getElementById('vodascript').text);
      // printScriptTextContent(document.getElementsById('vodascript'));
      getScript();
			window.my = true;
			// setVodapay(true);
		});
		script.src = 'https://appx/web-view.min.js';
		document.getElementsByTagName('head')[0].appendChild(script);
    alert('script created');
	}, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src='/vodapay.js' async />
      </Head>
      <Script src={'/vodapay.js'} />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <div className="">
        <p>
          <code>{text}</code>
        </p>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
