export const initialState = {
  resumableUpload: {
    showUploadBar: false,
    fullUploadView: false,
    totalPercent: 0,
    pendingQueue: [],
    completedQueue: [],
    uploadObj: {},
    status: 'idle'
  },
  stripeRegistration: {
    stripeURL: null,
    loading: false,
    cardDetails: null,
    dashboardURL: null,
  },
  celebrityToFollow: {
    error: '',
    celebId: null,
    celebProfessions: [],
    follow: null,
  },
  paymentDetails: {
    requestDetails: null,
    loading: false,
    requestPostLoading: false,
    paymentStatus: false,
    serverUpdated: false,
    error: null,
    requestError: null,
  },
  toastObj: {
    value: false,
    message: '',
    variant: '',
    time: 6000,
    global: true,
  },
  modals: {
    loginModal: {
      active: false,
      options: {},
    },
    signUpModal: false,
    quickViewModal: {
      active: false,
      data: null,
    },
    requestFlow: false,
    signupOptions: {},
    requestFlowDetails: null,
    bookingModal: {
      requestId: null,
      active: false,
      data: null,
      backLabel: '',
      starMode: false,
    },

    updateBookingModal: {
      active: false,
      requestId: null,
      requestData: {},
      onSuccess: () => {},
      renderProps: {},
    },
    supportModal: false,
    popUp: false,
    regCollector: false,
    mfpBanner: false,
  },
  filters: {
    category: {
      label: 'Featured',
      value: 0,
      subCategories: [],
      selected: [],
      selectString: '',
    },
    searchParam: '',
    products: '',
    countries: '',
    lowPrice: 0,
    highPrice: 500,
    regionCheck: false,
    sortValue: 'popularity',
    dynamicFilter: '',
    tag: {},
    needUpdate: false,
  },
  celebList: {
    data: [],
    loading: false,
    offset: -1,
    count: 0,
    limit: 72,
    currentCategory: 'featured',
    isLoggedIn: false,
    currentHash: '',
  },
  salesMessage: {
    messages: [],
    rowCount: {},
    loading: false,
    currentCat: null,
  },
  celebVideos: {
    data: [],
    loading: false,
    offset: -1,
    count: 0,
    limit: 20,
  },
  audioRecorder: {
    recorded: { from: null, for: null, host: null, honor: null },
  },
  purchaseFlow: {
    occasions: [],
    popularOccasions: [],
    loading: false,
    videoUploaded: false,
    bookingData: {
      templateType: null,
      relationship: [],
      user: 'someoneElse',
      enableAudioRecorder: false,
      hostName: '',
      userName: '',
      relationshipValue: '',
      specification: '',
      date: null,
      eventName: '',
      validSelf: false,
      occasion: {},
      scriptText: '',
      otherSelected: false,
      requestId: '',
      importantInfo: '',
      privateVideo: false,
    },
    formProps: {
      stepCount: 1,
      category: 0,
      termsCheck: false,
      privateVideo: false,
      importantInfo: '',
      edit: false,
      skipSelection: false,
    },
    productInfo: {
      formData: {
        shipping_full_name: '',
        shipping_address_1: '',
        shipping_address_2: '',
        shipping_city: '',
        shipping_state: '',
        shipping_zip_code: '',
        shipping_phone: '',
        description: '',
        country: 'US',
      },
      step: 1,
    },
  },
    commonReducer: {
      shouldRecord: false,
      videoSrc: null,
      file: null,
      recordedTime: '00:00',
      playPauseMedia: false,
      loader: false,
      customerId: null,
      videoUploaded: false,
      toastObj: {
        value: false,
        message: '',
        variant: '',
        time: 6000,
        global: true,
      },
      audioFlags: {
        recording: false,
        playing: false,
      },
      recorded: false,
      progress: {
        value: 5,
        loader: false,
      },
      justSignup: false,
      alertData: { open: false, type: '' },
      searchTerm: '',
      confirmSave: {
        saved: true,
        route: '',
      },
    },
    showHow: false
}

export const sessionInitialState = {
  generalData: {
    isLoggedIn: false,
    loading: false,
    auth_token: '',
    incorrectError: '',
    tempDetails: {},
    error: {
      has: false,
      message: '',
    },
    statusCode: undefined,
    errorCode: undefined,
    errorType: '',
    starRole: false,
    isRegistered: false,
    loginEmail: '',
  },
  userData: {
    name: ""
  },
  signupDetails: {
    role: '',
    currentStep: 0,
    disableRoleChange: false,
    acceptTerms: false,
    isSocial: false,
    source: '',
    firstName: '',
    lastName: '',
    nickName: '',
    email: '',
    password: '',
    profilePhoto: '',
    fbId: '',
    gpId: '',
    instId: '',
    twId: '',
    profileImage: null,
    categoryList: [],
    audioVideoSupport: true,
    welcomeVideoSkip: false,
    welcomeVideo: '',
    welcomeVideoFile: '',
    welcomeVideoLength: '',
    videoUploaded: false,
    price: '20',
    referral: '',
  }
}